
workflows:
  hill_climb_game_build:
    name: Hill Climb Game Build
    max_build_duration: 30
    environment:
      flutter: stable
      xcode: latest
      vars:
        PACKAGE_NAME: "com.example.hillclimbgame"
    scripts:
      - name: Get dependencies
        script: |
          flutter pub get
      - name: Run build for Android APK
        script: |
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
    publishing:
      email:
        recipients:
          - dilipjat440@gmail.com
        notify:
          success: true
          failure: true
